"""
generate_alignment_report.py

This script serves as the aggregation and reporting layer of the pipeline.
It synthesizes the raw outputs generated by `align.py` (conservation JSONs)
and `scan.py` (TFBS hits TSV) into comprehensive, text reports
and statistics.

By running this script, we transform thousands of individual genomic comparisons
into macroscopic summary metrics for the entire HAR dataset.
"""

import os
import json
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import argparse

_ROOT = Path(__file__).resolve().parent.parent
_RESULTS = _ROOT / "results"


def generate_alignment_statistics(alignments_dir, output_file="alignment_stats.txt"):
    """
    Parses all individual `.conservation.json` files to calculate global
    alignment statistics across the entire dataset (e.g., average conservation rate,
    total gaps, total substitutions).
    """

    # Initialize a dictionary to accumulate global metrics
    stats = {
        "total_hars": 0,
        "total_aligned_length": 0,
        "total_conserved": 0,
        "total_substitutions": 0,
        "total_gaps": 0,
        "conservation_rates": [],
    }

    har_details = []

    # Find all conservation track JSONs in the alignments directory
    conservation_files = sorted(Path(alignments_dir).glob("*.conservation.json"))

    for cons_file in conservation_files:
        with open(cons_file) as f:
            cons_data = json.load(f)

        # Extract HAR name from the filename
        har_name = cons_file.stem.replace(".conservation", "")
        aln_length = cons_data["aln_length"]
        track = cons_data["track"]

        # Count specific evolutionary events from the track array
        n_conserved = track.count("conserved")
        n_subs = track.count("substitution")
        n_gaps = track.count("gap_human") + track.count("gap_chimp")

        # Calculate the sequence identity (conservation rate) for this specific HAR
        cons_rate = n_conserved / aln_length if aln_length > 0 else 0

        # Accumulate metrics for the global summary
        stats["total_hars"] += 1
        stats["total_aligned_length"] += aln_length
        stats["total_conserved"] += n_conserved
        stats["total_substitutions"] += n_subs
        stats["total_gaps"] += n_gaps
        stats["conservation_rates"].append(cons_rate)

        # Store individual HAR data for the detailed table
        har_details.append(
            {
                "HAR": har_name,
                "Length": aln_length,
                "Conserved": n_conserved,
                "Substitutions": n_subs,
                "Gaps": n_gaps,
                "Conservation_Rate": f"{cons_rate:.2%}",
            }
        )

    # Write the accumulated statistics out to a formatted text file
    with open(output_file, "w") as f:
        f.write("=" * 70 + "\n")
        f.write("ALIGNMENT STATISTICS SUMMARY\n")
        f.write("=" * 70 + "\n\n")

        f.write(f"Total HARs analyzed: {stats['total_hars']}\n")
        f.write(f"Total aligned length: {stats['total_aligned_length']} bp\n")
        f.write(f"Total conserved positions: {stats['total_conserved']}\n")
        f.write(f"Total substitutions: {stats['total_substitutions']}\n")
        f.write(f"Total gaps: {stats['total_gaps']}\n\n")

        if stats["conservation_rates"]:
            avg_cons = np.mean(stats["conservation_rates"])
            f.write(f"Average conservation rate: {avg_cons:.2%}\n")
            f.write(f"Min conservation: {min(stats['conservation_rates']):.2%}\n")
            f.write(f"Max conservation: {max(stats['conservation_rates']):.2%}\n\n")

        f.write("=" * 70 + "\n")
        f.write("PER-HAR DETAILS\n")
        f.write("=" * 70 + "\n\n")

        # Use pandas to format the list of dictionaries into a clean text table
        details_df = pd.DataFrame(har_details)
        f.write(details_df.to_string(index=False))

    print(f"Statistics saved to {output_file}")
    return har_details


def generate_tfbs_statistics(tfbs_tsv, output_file="tfbs_stats.txt"):
    """
    Analyzes the TFBS hits TSV to determine which transcription factors are
    most prevalent, and categorizes them by species (human-specific, chimp-specific, shared).
    """

    # low_memory=False prevents mixed-type warnings for the chromosome/region column
    df = pd.read_csv(tfbs_tsv, sep="\t", low_memory=False)

    with open(output_file, "w") as f:
        f.write("=" * 70 + "\n")
        f.write("TFBS STATISTICS SUMMARY\n")
        f.write("=" * 70 + "\n\n")

        f.write(f"Total TFBS hits: {len(df)}\n")
        f.write(f"Unique TFs: {df['name'].nunique()}\n\n")

        # Compare total regulatory activity between species
        human_hits = len(df[df["species"] == "human"])
        chimp_hits = len(df[df["species"] == "chimp"])

        f.write(f"Human hits: {human_hits}\n")
        f.write(f"Chimp hits: {chimp_hits}\n\n")

        f.write("=" * 70 + "\n")
        f.write("TOP 20 TRANSCRIPTION FACTORS\n")
        f.write("=" * 70 + "\n\n")

        # Extract the 20 most frequently occurring TFs overall
        tf_counts = df["name"].value_counts().head(20)
        for tf, count in tf_counts.items():
            human_count = len(df[(df["name"] == tf) & (df["species"] == "human")])
            chimp_count = len(df[(df["name"] == tf) & (df["species"] == "chimp")])
            f.write(
                f"{tf:20s} Total: {count:4d}  (Human: {human_count:3d}, Chimp: {chimp_count:3d})\n"
            )

        f.write("\n")
        f.write("=" * 70 + "\n")
        f.write("SPECIES-SPECIFIC TFS\n")
        f.write("=" * 70 + "\n\n")

        # Use Python sets to easily find intersections (shared) and differences (species-specific)
        human_tfs = set(df[df["species"] == "human"]["name"])
        chimp_tfs = set(df[df["species"] == "chimp"]["name"])

        human_only = human_tfs - chimp_tfs
        chimp_only = chimp_tfs - human_tfs
        shared = human_tfs & chimp_tfs

        f.write(
            f"Human-specific TFs ({len(human_only)}): {', '.join(sorted(human_only)[:10])}\n"
        )
        if len(human_only) > 10:
            f.write(f"                  ... and {len(human_only) - 10} more\n")

        f.write(
            f"\nChimp-specific TFs ({len(chimp_only)}): {', '.join(sorted(chimp_only)[:10])}\n"
        )
        if len(chimp_only) > 10:
            f.write(f"                  ... and {len(chimp_only) - 10} more\n")

        f.write(
            f"\nShared TFs ({len(shared)}): {len(shared)} TFs present in both species\n"
        )

    print(f"TFBS statistics saved to {output_file}")


def create_pipeline_report(alignments_dir, tfbs_tsv, output_dir):
    """
    Main orchestrator function. Calls all the sub-functions to generate
    the full suite of reports and plots in the designated output folder.
    """

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    print("\n" + "=" * 70)
    print("GENERATING COMPREHENSIVE ALIGNMENT & TFBS ANALYSIS REPORT")
    print("=" * 70 + "\n")

    print("Generating alignment statistics...")
    generate_alignment_statistics(
        alignments_dir, os.path.join(output_dir, "alignment_statistics.txt")
    )

    print("Generating TFBS statistics...")
    generate_tfbs_statistics(tfbs_tsv, os.path.join(output_dir, "tfbs_statistics.txt"))

    print("\n" + "=" * 70)
    print("REPORT GENERATION COMPLETE")
    print("=" * 70)
    print(f"\nOutput directory: {output_dir}")
    print("\nGenerated files:")
    print("  - alignment_statistics.txt")
    print("  - tfbs_statistics.txt")
    print("\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate comprehensive alignment and TFBS analysis report"
    )
    parser.add_argument(
        "--alignments_dir",
        required=True,
        help="Directory with alignment outputs from align.py",
    )
    parser.add_argument("--tfbs", required=True, help="TFBS TSV file from scan.py")
    parser.add_argument(
        "--output_dir", default=str(_RESULTS / "analysis_report"), help="Output directory for report"
    )

    args = parser.parse_args()

    create_pipeline_report(args.alignments_dir, args.tfbs, args.output_dir)
